#!/usr/bin/env bash

# cadsoft_eagle_git_attributes
#
# Copyright 2016 Andrew Countryman <apcountryman@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# File: install
# Description: Install script for the CadSoft EAGLE git attributes.

function display_help {
    echo "NAME"
    echo "    install - install the CadSoft EAGLE git attributes"
    echo
    echo "SYNOPSIS"
    echo "    install --help"
    echo "    install --version"
    echo "    install --global"
    echo
    echo "OPTIONS"
    echo "    --help"
    echo "        Display this help."
    echo "    --version"
    echo "        Display version."
    echo "    --global"
    echo "        Write the attributes to the global git configuration file."
    echo
    echo "EXAMPLES"
    echo "    install --help"
    echo "    install --version"
    echo "    install --global"
}

# script version
VERSION="0.0.0"

# project clean filter
FILTER_PROJECT_CLEAN=\
'sed'\
' -e '"'"'/^\[Eagle\]\|^\[Globals\]/,/^\s*$/!d'"'"\
' -e '"'"'/^\[Eagle\]/,/^\s*$/{/^\[Eagle\]\|^Version=\|^Globals=\|^\s*$/!d;}'"'"\
' -e '"'"'/^\[Globals\]/,/^\s*$/{/^\s*$/d;}'"'"

# verify there are arguments
if [[ $# -eq 0 ]]; then
    ( >&2 echo "install: no arguments, aborting" )
    ( >&2 echo "install: try 'install --help' for more information" )
    exit 1

fi

# read in arguments
while [[ $# -gt 0 ]]; do
    option="$1"

    case $option in
        --help)
            display_help
            exit 0

        ;;
        --version)
            echo "initialize: version $VERSION"
            exit 0

        ;;
        --global)
            GLOBAL=true

        ;;
        --*|-)
            ( >&2 echo "install: unrecognized option '$option', aborting" )
            exit 1

        ;;

    esac

    shift

done

if [[ -z $GLOBAL ]]; then
    ( >&2 echo "install: attributes scope not specified, aborting" )
    exit 1

fi

if [[ "$GLOBAL" == true ]]; then
    SCOPE="--global"

fi

# install the project filter
git config "$SCOPE" filter.cadsoft_eagle_project.clean "$FILTER_PROJECT_CLEAN"

if [[ $? != 0 ]]; then
    exit 1

fi

exit 0
