#!/usr/bin/env bash

# cadsoft_eagle_git_attributes
#
# Copyright 2016 Andrew Countryman <apcountryman@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# File: install
# Description: Git hooks install script for the CadSoft EAGLE git attributes repository.

# hooks path
SCRIPT=$( readlink -f $0 )
HOOKS_DIR=$( dirname $SCRIPT )

# install path
INSTALL_DIR="$HOOKS_DIR"/../.git/hooks

# list of hooks to install
HOOKS=pre-commit

for hook in "$HOOKS"; do
    echo -n "install: installing $hook hook ... "

    # delete any existing hook
    rm -f "$INSTALL_DIR"/"$hook"

    # abort if the hook script is missing or non-executable
    if [[ ! -x "$HOOKS_DIR"/"$hook" ]]; then
        echo "error"
        ( >&2 echo "install: aborting install due to missing or non-executable $hook hook script" )
        exit 1

    fi

    # create the symbolic link for the hook
    ln -s "$HOOKS_DIR"/"$hook" "$INSTALL_DIR"/"$hook"

    # abort if the symbolic link was not created
    if [[ $? != 0 ]]; then
        echo "error"
        ( >&2 echo "install: aborting install due to $hook hook symbolic link creation failure" )
        exit 1

    fi

    echo "complete"

done

exit 0
