#!/usr/bin/env bash

# cadsoft_eagle_git_attributes
#
# Copyright 2016 Andrew Countryman <apcountryman@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# File: pre-commit
# Description: Pre-commit git hook script for the CadSoft EAGLE git attributes
#              repository.

# hooks path
SCRIPT=$( readlink -f $0 )
HOOKS_DIR=$( dirname $SCRIPT )

# repository root directory
ROOT_DIR="$HOOKS_DIR"/..

# verify there are no whitespace errors
echo -n "pre-commit: checking for whitespace errors ..... "

git diff-index --check HEAD
if [[ $? != 0 ]]; then
    echo "error(s) found"
    ( >&2 echo "pre-commit: aborting commit due to whitespace error(s)" )
    exit 1

fi

echo "none"

exit 0
